-- migrations/2026-08-18-taskflow-state-identity.sql
-- ================================================================
-- Convierte public.taskflow_state.id de "integer NOT NULL DEFAULT 1"
-- a "integer NOT NULL GENERATED BY DEFAULT AS IDENTITY" con la
-- secuencia arrancando en MAX(id)+1 (calculado dinámicamente).
--
-- CONTEXTO:
--   Tras aplicar 2026-08-18-tenants-signup-columns.sql y quitar el
--   email del INSERT a tenant_members (commit 7cf5f87), /api/signup
--   avanzó hasta el paso 5 y falló:
--     "duplicate key value violates unique constraint taskflow_state_pkey"
--
--   Causa raíz: id tiene DEFAULT literal 1 (no SERIAL, no IDENTITY).
--   Cada INSERT nuevo intenta id=1 y choca con la fila crown-jewel
--   del tenant fundacional. Las altas manuales de Luis Granda y
--   Robert se hicieron precisamente por este motivo — hardcodeando
--   ids 2 y 3 a mano.
--
--   Verificado desde schema-01-columns.csv del backup 2026-08-18:
--     id integer NOT NULL default 1
--   Verificado con MAX(id) = 3, COUNT(*) = 3, ids 1/2/3 sin huecos.
--
-- GARANTÍA DE INTEGRIDAD:
--   Este script SOLO modifica el atributo DEFAULT/IDENTITY de la
--   columna id (metadato de esquema en pg_attribute + pg_attrdef).
--   No ejecuta ningún UPDATE, DELETE ni ALTER sobre valores de fila.
--   Las 3 filas existentes con sus JSONB de tenant conservan bit a
--   bit su estado actual porque NINGUNA sentencia del script las
--   referencia. El paso "ALTER COLUMN DROP DEFAULT" solo borra la
--   entrada de pg_attrdef; los ids 1, 2, 3 siguen guardados en las
--   filas. El paso "ADD GENERATED AS IDENTITY" crea una nueva
--   secuencia y la asocia como generador; INSERTs futuros toman
--   nextval de esa secuencia. Existentes quedan intocados.
--
-- ELECCIÓN "BY DEFAULT" (no "ALWAYS"):
--   Permite seguir insertando con id explícito en el futuro (útil
--   para restauraciones de backup o migraciones cross-tenant). El
--   generador solo actúa cuando el INSERT no proporciona id.
--
-- CONCURRENCIA:
--   Sequences en Postgres son transaction-safe. Dos INSERTs paralelos
--   obtienen ids distintos atómicamente. La race condition de Opción B
--   (SELECT MAX + INSERT) desaparece.
--
-- LOCK:
--   ALTER COLUMN DROP DEFAULT y ADD GENERATED toman AccessExclusiveLock
--   sobre la tabla, pero son operaciones de metadata (no reescriben
--   filas). Duración esperada <100 ms sobre tabla de 3 filas. Cualquier
--   UPDATE concurrente de sync.js espera; ninguno se pierde.
--
-- ROLLBACK: al final del fichero, comentado.
-- ================================================================


BEGIN;


-- ── 1. Quitar el DEFAULT literal 1 ───────────────────────────────
-- Prerequisito para poder añadir IDENTITY (Postgres rechaza ADD
-- IDENTITY sobre columna que ya tiene DEFAULT). No toca valores.
ALTER TABLE public.taskflow_state
  ALTER COLUMN id DROP DEFAULT;


-- ── 2. Convertir a IDENTITY con START dinámico ───────────────────
-- Cálculo dinámico dentro de un bloque PL/pgSQL: leemos MAX(id) en
-- runtime, sumamos 1, y ejecutamos el ALTER via EXECUTE format() —
-- así el SQL es reutilizable en cualquier entorno donde MAX difiera
-- (dev, preview, prod). Sin hardcodeos.
DO $$
DECLARE
  next_id integer;
BEGIN
  SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.taskflow_state;
  RAISE NOTICE '[taskflow_state] MAX(id) actual → sequence START WITH %', next_id;
  EXECUTE format(
    'ALTER TABLE public.taskflow_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
    next_id
  );
END $$;


-- ── 3. Refrescar cache de PostgREST ──────────────────────────────
-- Sin este NOTIFY, /api/signup seguiría intentando DEFAULT 1 hasta
-- que PostgREST reciclara solo.
NOTIFY pgrst, 'reload schema';


COMMIT;


-- ================================================================
-- VERIFICACIÓN POST-APLICACIÓN (queries separadas, solo lectura):
-- ================================================================
--
-- -- 1. La columna id ahora es IDENTITY (identity_generation != '')
-- SELECT column_name, data_type, is_nullable, column_default,
--        is_identity, identity_generation, identity_start
-- FROM information_schema.columns
-- WHERE table_schema='public' AND table_name='taskflow_state'
--   AND column_name='id';
-- -- Esperado:
-- --   data_type=integer, is_nullable=NO
-- --   column_default=nextval('taskflow_state_id_seq'::regclass)
-- --   is_identity=YES, identity_generation=BY DEFAULT
-- --   identity_start=4 (o MAX(id)+1 real)
--
-- -- 2. Secuencia existe y su próximo valor es MAX(id)+1
-- SELECT sequence_name, start_value, increment, minimum_value
-- FROM information_schema.sequences
-- WHERE sequence_schema='public'
--   AND sequence_name LIKE 'taskflow_state%';
--
-- -- 3. Los 3 tenants existentes intactos (ids 1/2/3, JSONB no vacío)
-- SELECT id, tenant_id, jsonb_typeof(data) AS data_type,
--        pg_column_size(data) AS bytes, updated_at
-- FROM public.taskflow_state
-- ORDER BY id;
-- -- Esperado: 3 filas con ids 1, 2, 3. data_type='object' en las 3.
-- --           bytes similar al pre-migración (2-3 MB por tenant).
-- --           tenant_id no NULL en las 3. updated_at intacto.
--
-- -- 4. Simulacro de INSERT (usando ROLLBACK para NO persistir):
-- BEGIN;
-- INSERT INTO public.taskflow_state (tenant_id, data)
-- VALUES ('00000000-0000-0000-0000-000000000000'::uuid, '{"probe":true}'::jsonb)
-- RETURNING id;
-- -- Esperado: id = MAX(id)+1 al momento del script (probablemente 4).
-- ROLLBACK;   -- <-- crítico: no dejamos la fila probe en producción.
--
-- ================================================================


-- ================================================================
-- ROLLBACK (solo si algo va mal — ejecutar en SQL Editor manualmente):
-- ================================================================
--
-- BEGIN;
-- ALTER TABLE public.taskflow_state ALTER COLUMN id DROP IDENTITY IF EXISTS;
-- ALTER TABLE public.taskflow_state ALTER COLUMN id SET DEFAULT 1;
-- NOTIFY pgrst, 'reload schema';
-- COMMIT;
--
-- Efectos del rollback:
--   - La columna id vuelve al estado pre-migración: DEFAULT literal 1.
--   - La secuencia taskflow_state_id_seq se destruye (DROP IDENTITY
--     hace ambos: quita el atributo IDENTITY y borra la secuencia
--     que Postgres creó automáticamente).
--   - Los ids existentes 1, 2, 3 se preservan (nadie los toca).
--   - /api/signup volverá a fallar con "duplicate key" hasta re-aplicar.
--   - Si /api/signup insertó tenants nuevos entre la migración y el
--     rollback, esas filas conservan sus ids (4, 5, ...) — no colisionan.
--   - NO afecta a data, tenant_id, updated_at ni a otras tablas.
--
-- Si el rollback también fallara (muy improbable): restaurar desde
-- ~/Desktop/kluxor-backup-2026-08-18/ (7 CSVs de datos + 5 CSVs de
-- schema descargados hoy antes de esta migración).
--
-- ================================================================
